import { MigrationBuilder } from 'node-pg-migrate';
interface Product {
  proteins: number;
  carbohydrates: number;
  fats: number;
  name: string;
  calories: number;
}
function getUniqueItems(array: Product[], propertyName: keyof Product): Product[] {
  const uniqueItems: Product[] = [];
  const seen = new Map<string | number, boolean>();

  for (const item of array) {
    const propertyValue = item[propertyName];

    if (!seen.has(propertyValue)) {
      seen.set(propertyValue, true);
      uniqueItems.push(item);
    }
  }

  return uniqueItems;
}
const db = [
  {
    proteins: 20,
    carbohydrates: 0.5,
    fats: 22,
    name: 'Camembert de Campagne',
    calories: 205.44,
  },
  {
    proteins: 19,
    carbohydrates: 0,
    fats: 20,
    name: 'Camembert President',
    calories: 186.78,
  },
  {
    proteins: 11.5,
    carbohydrates: 73,
    fats: 1.5,
    name: 'Canneloni',
    calories: 17.41,
  },
  {
    proteins: 7.5,
    carbohydrates: 26.8,
    fats: 19.1,
    name: 'Cheese Puffs',
    calories: 179.04,
  },
  {
    proteins: 1.5,
    carbohydrates: 6.1,
    fats: 0.2,
    name: 'Cherry tomatoes metro chef',
    calories: 2.17,
  },
  {
    proteins: 8.6,
    carbohydrates: 49.5,
    fats: 37.3,
    name: 'Kinder bueno',
    calories: 349.27,
  },
  {
    proteins: 8.2,
    carbohydrates: 56.5,
    fats: 32,
    name: 'Kinder joy',
    calories: 300.25,
  },
  {
    proteins: 7.9,
    carbohydrates: 34,
    fats: 27.9,
    name: 'Kinder milk slice',
    calories: 261.19,
  },
  {
    proteins: 4.9,
    carbohydrates: 45.7,
    fats: 26.3,
    name: 'Kinder pengui карамель',
    calories: 246.66,
  },
  {
    proteins: 0.1,
    carbohydrates: 85.5,
    fats: 5.4,
    name: 'Mamba ',
    calories: 53.73,
  },
  {
    proteins: 4,
    carbohydrates: 5.3,
    fats: 35,
    name: 'Mascarpone',
    calories: 325.88,
  },
  {
    proteins: 25,
    carbohydrates: 0,
    fats: 35,
    name: 'Matured cheese ',
    calories: 326.53,
  },
  {
    proteins: 6.7,
    carbohydrates: 50,
    fats: 28,
    name: 'Milka choko snack',
    calories: 262.72,
  },
  {
    proteins: 27,
    carbohydrates: 12,
    fats: 48,
    name: 'Peanut butter ',
    calories: 448,
  },
  {
    proteins: 12.2,
    carbohydrates: 71.5,
    fats: 2,
    name: 'Piccolini Barilla',
    calories: 22.03,
  },
  {
    proteins: 9.4,
    carbohydrates: 18.68,
    fats: 7.77,
    name: 'Picollini Barilla с тушенкой и сыром',
    calories: 73.42,
  },
  {
    proteins: 10,
    carbohydrates: 3.2,
    fats: 9,
    name: 'Ricotta',
    calories: 84.24,
  },
  {
    proteins: 8.4,
    carbohydrates: 39,
    fats: 41,
    name: 'Rittersport черный с орехом',
    calories: 383.24,
  },
  {
    proteins: 4,
    carbohydrates: 61.9,
    fats: 26,
    name: 'Roshen Lovita choko',
    calories: 244.5,
  },
  {
    proteins: 10,
    carbohydrates: 52,
    fats: 24,
    name: 'Roshen драже с арахисом',
    calories: 225.74,
  },
  {
    proteins: 11,
    carbohydrates: 0.2,
    fats: 1.5,
    name: 'Simmenthal тушенка',
    calories: 14.41,
  },
  {
    proteins: 8.6,
    carbohydrates: 60.5,
    fats: 22.5,
    name: 'Snickers ',
    calories: 212.08,
  },
  {
    proteins: 8.1,
    carbohydrates: 59.9,
    fats: 23.5,
    name: 'Snickers с фундуком',
    calories: 221.34,
  },
  {
    proteins: 0.14,
    carbohydrates: 19.61,
    fats: 0.55,
    name: 'Spahettini вареные',
    calories: 5.95,
  },
  {
    proteins: 0.5,
    carbohydrates: 70.9,
    fats: 2,
    name: 'Spahettini сырые',
    calories: 21.53,
  },
  {
    proteins: 2.6,
    carbohydrates: 49,
    fats: 3.2,
    name: 'Tagliolini',
    calories: 31.88,
  },
  {
    proteins: 1.33,
    carbohydrates: 25.05,
    fats: 1.64,
    name: 'Tagliolini вареные',
    calories: 16.3,
  },
  {
    proteins: 9.9,
    carbohydrates: 46,
    fats: 4.5,
    name: 'Tost 3 ziarna',
    calories: 44.14,
  },
  {
    proteins: 8.1,
    carbohydrates: 71.6,
    fats: 9.8,
    name: 'Yarych Марія висівки',
    calories: 94.41,
  },
  {
    proteins: 7.9,
    carbohydrates: 74.4,
    fats: 9.4,
    name: 'Yarych Марія класична',
    calories: 90.79,
  },
  {
    proteins: 0.9,
    carbohydrates: 10.5,
    fats: 0.4,
    name: 'Абрикоси',
    calories: 4.19,
  },
  {
    proteins: 7.5,
    carbohydrates: 10.5,
    fats: 3.9,
    name: 'Агуша абрикос морква',
    calories: 37.01,
  },
  {
    proteins: 0.6,
    carbohydrates: 8.9,
    fats: 0.1,
    name: 'Груші',
    calories: 1.32,
  },
  {
    proteins: 0.2,
    carbohydrates: 7.4,
    fats: 0.1,
    name: 'Алича',
    calories: 1.24,
  },
  {
    proteins: 0.4,
    carbohydrates: 11.8,
    fats: 0.1,
    name: 'Ананаси',
    calories: 1.43,
  },
  {
    proteins: 0.9,
    carbohydrates: 8.4,
    fats: 0.2,
    name: 'Апельсини',
    calories: 2.24,
  },
  {
    proteins: 26.3,
    carbohydrates: 9.7,
    fats: 45.2,
    name: 'Арахіс',
    calories: 421.84,
  },
  {
    proteins: 26,
    carbohydrates: 10,
    fats: 45,
    name: 'Арахісова паста з шоколадом',
    calories: 419.98,
  },
  {
    proteins: 0.6,
    carbohydrates: 8,
    fats: 0.2,
    name: 'Кавун',
    calories: 2.21,
  },
  {
    proteins: 0.6,
    carbohydrates: 5.5,
    fats: 0.1,
    name: 'Баклажани',
    calories: 1.18,
  },
  {
    proteins: 84,
    carbohydrates: 5.2,
    fats: 1.6,
    name: 'Банановий протеїн',
    calories: 18.54,
  },
  {
    proteins: 1.5,
    carbohydrates: 22.4,
    fats: 0.3,
    name: 'Банани',
    calories: 3.77,
  },
  {
    proteins: 16.3,
    carbohydrates: 0,
    fats: 15.3,
    name: 'Баранина',
    calories: 142.96,
  },
  {
    proteins: 13.5,
    carbohydrates: 0,
    fats: 2.5,
    name: 'Бараняче Серце',
    calories: 23.8,
  },
  {
    proteins: 13.6,
    carbohydrates: 0,
    fats: 2.5,
    name: 'Баранячі Нирки',
    calories: 23.81,
  },
  {
    proteins: 18.7,
    carbohydrates: 0,
    fats: 2.9,
    name: 'Бараняча Печінка',
    calories: 27.74,
  },
  {
    proteins: 7.7,
    carbohydrates: 54.5,
    fats: 3,
    name: 'Батон сіхівський',
    calories: 30.45,
  },
  {
    proteins: 13,
    carbohydrates: 0,
    fats: 42,
    name: 'Бекон',
    calories: 391.13,
  },
  {
    proteins: 5.66,
    carbohydrates: 29.48,
    fats: 15.19,
    name: 'Бельгійські вафлі',
    calories: 142.72,
  },
  {
    proteins: 10.33,
    carbohydrates: 17.98,
    fats: 15.25,
    name: 'Бельгійські вафлі з творогом',
    calories: 142.99,
  },
  {
    proteins: 8,
    carbohydrates: 13,
    fats: 15,
    name: 'Бендерики',
    calories: 140.36,
  },
  {
    proteins: 2,
    carbohydrates: 54.89,
    fats: 15.11,
    name: 'Бісквітний рулет з лимонним курдом',
    calories: 142.89,
  },
  {
    proteins: 8,
    carbohydrates: 34,
    fats: 3,
    name: 'Млинці 50/50',
    calories: 29.62,
  },
  {
    proteins: 4.05,
    carbohydrates: 22.61,
    fats: 1.91,
    name: 'Млинці на білому борошні з рослинним молоком',
    calories: 18.84,
  },
  {
    proteins: 4.45,
    carbohydrates: 18.49,
    fats: 2.42,
    name: 'Млинці на білому борошні зі стевією',
    calories: 23.42,
  },
  {
    proteins: 6.25,
    carbohydrates: 21.07,
    fats: 6.85,
    name: 'Млинці рецепт',
    calories: 64.79,
  },
  {
    proteins: 6,
    carbohydrates: 8.3,
    fats: 0.1,
    name: 'Боби',
    calories: 1.52,
  },
  {
    proteins: 2.6,
    carbohydrates: 3.4,
    fats: 1.8,
    name: 'Борщ',
    calories: 16.99,
  },
  {
    proteins: 3.28,
    carbohydrates: 4.65,
    fats: 0.66,
    name: 'Броколі',
    calories: 6.46,
  },
  {
    proteins: 0.7,
    carbohydrates: 8.6,
    fats: 0.5,
    name: 'Брусника',
    calories: 5.03,
  },
  {
    proteins: 17.9,
    carbohydrates: 0,
    fats: 20.1,
    name: 'Бринза з коровʼячого молока',
    calories: 187.66,
  },
  {
    proteins: 20,
    carbohydrates: 0,
    fats: 12,
    name: 'Бринка болгарська Metro chef',
    calories: 112.42,
  },
  {
    proteins: 9.6,
    carbohydrates: 73.8,
    fats: 10.9,
    name: 'Бублики сушка',
    calories: 104.79,
  },
  {
    proteins: 3,
    carbohydrates: 18,
    fats: 0.24,
    name: 'Бульгур варений',
    calories: 3.09,
  },
  {
    proteins: 7.9,
    carbohydrates: 55.5,
    fats: 9.4,
    name: 'Булочка сдобна',
    calories: 90.02,
  },
  {
    proteins: 11.13,
    carbohydrates: 19.61,
    fats: 33.32,
    name: 'Бутерброд (хліб, сало, сир)',
    calories: 311.14,
  },
  {
    proteins: 5.1,
    carbohydrates: 30,
    fats: 4.7,
    name: 'Вареники з картоплею',
    calories: 45.15,
  },
  {
    proteins: 5.2,
    carbohydrates: 38,
    fats: 1.6,
    name: 'Вареники з вишнею',
    calories: 16.65,
  },
  {
    proteins: 5.1,
    carbohydrates: 30,
    fats: 4.7,
    name: 'Вареники з картоплею',
    calories: 45.15,
  },
  {
    proteins: 0.4,
    carbohydrates: 68,
    fats: 0.3,
    name: 'Варенье',
    calories: 5.59,
  },
  {
    proteins: 0.4,
    carbohydrates: 17.5,
    fats: 0.4,
    name: 'Виноград',
    calories: 4.45,
  },
  {
    proteins: 0.8,
    carbohydrates: 11.3,
    fats: 0.3,
    name: 'Вишня',
    calories: 3.29,
  },
  {
    proteins: 1.5,
    carbohydrates: 73,
    fats: 0.5,
    name: 'Вишня сушена',
    calories: 7.7,
  },
  {
    proteins: 0,
    carbohydrates: 0,
    fats: 0,
    name: 'Вода',
    calories: 0,
  },
  {
    proteins: 9.4,
    carbohydrates: 44.25,
    fats: 4.26,
    name: 'Галин хліб',
    calories: 41.82,
  },
  {
    proteins: 13,
    carbohydrates: 30,
    fats: 9,
    name: 'Гамбургер',
    calories: 85.46,
  },
  {
    proteins: 13.1,
    carbohydrates: 65.7,
    fats: 6.2,
    name: 'Геркулес',
    calories: 60.89,
  },
  {
    proteins: 0,
    carbohydrates: 100,
    fats: 0,
    name: 'Глюкоза',
    calories: 4.1,
  },
  {
    proteins: 26,
    carbohydrates: 0,
    fats: 15,
    name: 'Говядина',
    calories: 140.57,
  },
  {
    proteins: 13.6,
    carbohydrates: 0,
    fats: 12.1,
    name: 'Говяжий язик',
    calories: 113.09,
  },
  {
    proteins: 12.3,
    carbohydrates: 0,
    fats: 13.7,
    name: 'Говяжа вимʼя',
    calories: 127.91,
  },
  {
    proteins: 15,
    carbohydrates: 0,
    fats: 3,
    name: 'Говяже серце',
    calories: 28.52,
  },
  {
    proteins: 9.5,
    carbohydrates: 0,
    fats: 9.5,
    name: 'Говяжі мозки',
    calories: 88.74,
  },
  {
    proteins: 12.5,
    carbohydrates: 0,
    fats: 1.8,
    name: 'Говяжі нирки',
    calories: 17.25,
  },
  {
    proteins: 17.4,
    carbohydrates: 0,
    fats: 3.1,
    name: 'Говяжа печінка',
    calories: 29.54,
  },
  {
    proteins: 1,
    carbohydrates: 7.7,
    fats: 0.3,
    name: 'Голубика',
    calories: 3.15,
  },
  {
    proteins: 7.1,
    carbohydrates: 10.9,
    fats: 11.54,
    name: 'Голубці Галя Балувана',
    calories: 108.06,
  },
  {
    proteins: 21,
    carbohydrates: 0,
    fats: 7,
    name: 'Горбуша',
    calories: 65.96,
  },
  {
    proteins: 23,
    carbohydrates: 57.7,
    fats: 1.6,
    name: 'Горох лущений',
    calories: 18.19,
  },
  {
    proteins: 23,
    carbohydrates: 53.3,
    fats: 1.2,
    name: 'Горох цілий',
    calories: 14.29,
  },
  {
    proteins: 5,
    carbohydrates: 13.3,
    fats: 0.2,
    name: 'Горошина зелена',
    calories: 2.61,
  },
  {
    proteins: 0.9,
    carbohydrates: 11.8,
    fats: 1.2,
    name: 'Гранат',
    calories: 11.68,
  },
  {
    proteins: 1,
    carbohydrates: 17,
    fats: 0.32,
    name: 'Гранатовий соус',
    calories: 3.71,
  },
  {
    proteins: 0.9,
    carbohydrates: 7.3,
    fats: 0.1,
    name: 'Грейпфрут',
    calories: 1.27,
  },
  {
    proteins: 13.8,
    carbohydrates: 10.2,
    fats: 61.3,
    name: 'Грецький горіх',
    calories: 571.07,
  },
  {
    proteins: 3.83,
    carbohydrates: 20.7,
    fats: 0.79,
    name: 'Гречка варена',
    calories: 8.36,
  },
  {
    proteins: 4.65,
    carbohydrates: 23.04,
    fats: 2.18,
    name: 'Гречка варена old',
    calories: 21.41,
  },
  {
    proteins: 12.6,
    carbohydrates: 68,
    fats: 2.6,
    name: 'Гречкова крупа',
    calories: 27.48,
  },
  {
    proteins: 3.2,
    carbohydrates: 1.6,
    fats: 0.7,
    name: 'Гриби Білі свіжі',
    calories: 6.71,
  },
  {
    proteins: 27.6,
    carbohydrates: 10,
    fats: 6.8,
    name: 'Гриби Білі сушені',
    calories: 64.78,
  },
  {
    proteins: 2.3,
    carbohydrates: 3.7,
    fats: 0.9,
    name: 'Гриби Підберезовики свіжі',
    calories: 8.62,
  },
  {
    proteins: 3.3,
    carbohydrates: 3.4,
    fats: 0.5,
    name: 'Гриби Підосиновики свіжі',
    calories: 4.92,
  },
  {
    proteins: 1.7,
    carbohydrates: 1.4,
    fats: 0.3,
    name: 'Гриби Сироїжки свіжі',
    calories: 2.92,
  },
  {
    proteins: 0.4,
    carbohydrates: 10.7,
    fats: 0.1,
    name: 'Груша',
    calories: 1.39,
  },
  {
    proteins: 2.3,
    carbohydrates: 62.1,
    fats: 0.5,
    name: 'Груша сушена',
    calories: 7.29,
  },
  {
    proteins: 16.1,
    carbohydrates: 0,
    fats: 33.3,
    name: 'Гуси',
    calories: 310.35,
  },
  {
    proteins: 27,
    carbohydrates: 31,
    fats: 23,
    name: 'Дабл Чізбургер',
    calories: 216.28,
  },
  {
    proteins: 6.26,
    carbohydrates: 51.68,
    fats: 21.64,
    name: 'Домашнє печиво',
    calories: 203.64,
  },
  {
    proteins: 8.72,
    carbohydrates: 48.41,
    fats: 22.45,
    name: 'Домашнє овесне печиво',
    calories: 211.12,
  },
  {
    proteins: 0.8,
    carbohydrates: 8,
    fats: 0.2,
    name: 'Диня',
    calories: 2.22,
  },
  {
    proteins: 2,
    carbohydrates: 10,
    fats: 0.5,
    name: 'Ожина',
    calories: 5.14,
  },
  {
    proteins: 4.02,
    carbohydrates: 7.25,
    fats: 5.71,
    name: 'Жарке зі сметаною',
    calories: 53.59,
  },
  {
    proteins: 6.05,
    carbohydrates: 12.93,
    fats: 10.26,
    name: 'Жарке томатне зі сметаною',
    calories: 96.22,
  },
  {
    proteins: 6.5,
    carbohydrates: 75.4,
    fats: 0.2,
    name: 'Залізні конфети',
    calories: 5.22,
  },
  {
    proteins: 0,
    carbohydrates: 93,
    fats: 0,
    name: 'Загущувач для вершків',
    calories: 3.81,
  },
  {
    proteins: 13.07,
    carbohydrates: 5.1,
    fats: 10.74,
    name: 'Запіканка з чорницею',
    calories: 100.63,
  },
  {
    proteins: 4,
    carbohydrates: 4.3,
    fats: 0.1,
    name: 'Зелена фасоль (стручок)',
    calories: 1.27,
  },
  {
    proteins: 1.8,
    carbohydrates: 8.1,
    fats: 0.3,
    name: 'Малина',
    calories: 3.2,
  },
  {
    proteins: 0.8,
    carbohydrates: 78.3,
    fats: 0,
    name: 'Зефір',
    calories: 3.24,
  },
  {
    proteins: 11.15,
    carbohydrates: 2.26,
    fats: 10.49,
    name: 'Запаска для жаркого',
    calories: 98.12,
  },
  {
    proteins: 12,
    carbohydrates: 4,
    fats: 18,
    name: 'Запаска для жаркого томат + сметана',
    calories: 168.06,
  },
  {
    proteins: 3.8,
    carbohydrates: 19,
    fats: 8,
    name: 'Зрази картопляні',
    calories: 75.33,
  },
  {
    proteins: 2.3,
    carbohydrates: 71.2,
    fats: 0.5,
    name: 'Розини',
    calories: 7.66,
  },
  {
    proteins: 0.78,
    carbohydrates: 5.55,
    fats: 0.11,
    name: 'Ікра з баклажанів',
    calories: 1.27,
  },
  {
    proteins: 21.6,
    carbohydrates: 0.8,
    fats: 12,
    name: 'Індичка',
    calories: 112.52,
  },
  {
    proteins: 0.7,
    carbohydrates: 13.9,
    fats: 0.1,
    name: 'Інжир',
    calories: 1.53,
  },
  {
    proteins: 3.3,
    carbohydrates: 81.8,
    fats: 7.5,
    name: 'Ірис',
    calories: 73.24,
  },
  {
    proteins: 3.6,
    carbohydrates: 5,
    fats: 9,
    name: 'Йогурт грецький',
    calories: 84.05,
  },
  {
    proteins: 5,
    carbohydrates: 3.5,
    fats: 1.5,
    name: 'Йогурт натуральний 1.5% жирності',
    calories: 14.3,
  },
  {
    proteins: 2.29,
    carbohydrates: 9.39,
    fats: 1.73,
    name: 'Гарбузова каша',
    calories: 16.55,
  },
  {
    proteins: 0.6,
    carbohydrates: 5.7,
    fats: 0.3,
    name: 'Гарбузи',
    calories: 3.05,
  },
  {
    proteins: 3.41,
    carbohydrates: 4.34,
    fats: 6.45,
    name: 'Гарбузи в духовці з помідорами і сиром',
    calories: 60.31,
  },
  {
    proteins: 19.4,
    carbohydrates: 9.1,
    fats: 23,
    name: 'Какао',
    calories: 215.07,
  },
  {
    proteins: 18,
    carbohydrates: 0,
    fats: 0.3,
    name: 'Кальмар',
    calories: 3.53,
  },
  {
    proteins: 16.1,
    carbohydrates: 0,
    fats: 2.6,
    name: 'Камбала',
    calories: 24.84,
  },
  {
    proteins: 14.27,
    carbohydrates: 7.05,
    fats: 10.58,
    name: 'Канелони з сиром',
    calories: 99.26,
  },
  {
    proteins: 1.3,
    carbohydrates: 6,
    fats: 0.1,
    name: 'Капуста',
    calories: 1.23,
  },
  {
    proteins: 1.8,
    carbohydrates: 6.1,
    fats: 0.1,
    name: 'Капуста червонокачана',
    calories: 1.25,
  },
  {
    proteins: 5,
    carbohydrates: 5,
    fats: 7,
    name: 'Капуста тушкована',
    calories: 65.51,
  },
  {
    proteins: 17.7,
    carbohydrates: 0,
    fats: 1.8,
    name: 'Карась',
    calories: 17.47,
  },
  {
    proteins: 16,
    carbohydrates: 0,
    fats: 3.6,
    name: 'Карп',
    calories: 34.14,
  },
  {
    proteins: 2.17,
    carbohydrates: 16.53,
    fats: 0.65,
    name: 'Картопля варена',
    calories: 6.81,
  },
  {
    proteins: 2,
    carbohydrates: 16,
    fats: 0.4,
    name: 'Картопля сирова',
    calories: 4.46,
  },
  {
    proteins: 1.7,
    carbohydrates: 15,
    fats: 2.8,
    name: 'Картопляне пюре',
    calories: 26.72,
  },
  {
    proteins: 3,
    carbohydrates: 19,
    fats: 6,
    name: 'Картопля смажена для жаркого',
    calories: 56.7,
  },
  {
    proteins: 2,
    carbohydrates: 19,
    fats: 5,
    name: 'Картопля смажена для жаркого',
    calories: 47.36,
  },
  {
    proteins: 3.31,
    carbohydrates: 18.81,
    fats: 0.54,
    name: 'Каша пшенична',
    calories: 5.93,
  },
  {
    proteins: 7.48,
    carbohydrates: 37.2,
    fats: 23.87,
    name: 'Кекс домашній з цукром',
    calories: 223.79,
  },
  {
    proteins: 5.75,
    carbohydrates: 32.61,
    fats: 20.01,
    name: 'Кекси кабачкові',
    calories: 187.67,
  },
  {
    proteins: 22,
    carbohydrates: 0,
    fats: 5.6,
    name: 'Кета',
    calories: 52.98,
  },
  {
    proteins: 1.4,
    carbohydrates: 12,
    fats: 0.1,
    name: 'Кетчуп Heinz kids',
    calories: 1.48,
  },
  {
    proteins: 2.8,
    carbohydrates: 4.1,
    fats: 3.2,
    name: 'Кефір жирний',
    calories: 30.04,
  },
  {
    proteins: 3,
    carbohydrates: 3.8,
    fats: 0.1,
    name: 'Кефір нежирний',
    calories: 1.21,
  },
  {
    proteins: 18,
    carbohydrates: 30,
    fats: 44,
    name: 'Кешʼю',
    calories: 411.17,
  },
  {
    proteins: 1,
    carbohydrates: 10.3,
    fats: 0.6,
    name: 'Ківі',
    calories: 6.04,
  },
  {
    proteins: 9.76,
    carbohydrates: 12.19,
    fats: 20.31,
    name: 'Кіш фета',
    calories: 189.79,
  },
  {
    proteins: 0.7,
    carbohydrates: 8,
    fats: 0.3,
    name: 'Полуниця',
    calories: 3.15,
  },
  {
    proteins: 0.5,
    carbohydrates: 4.8,
    fats: 0.1,
    name: 'Клюква',
    calories: 1.15,
  },
  {
    proteins: 13,
    carbohydrates: 14,
    fats: 65,
    name: 'Кокосова стружка',
    calories: 605.61,
  },
  {
    proteins: 20.2,
    carbohydrates: 0,
    fats: 7,
    name: 'Конина',
    calories: 65.93,
  },
  {
    proteins: 2.9,
    carbohydrates: 76.6,
    fats: 10.7,
    name: 'Цукерки глазуровані шоколадом',
    calories: 102.77,
  },
  {
    proteins: 9,
    carbohydrates: 56,
    fats: 6,
    name: 'Коржі бісквітні',
    calories: 58.47,
  },
  {
    proteins: 13.27,
    carbohydrates: 6.78,
    fats: 21.81,
    name: 'Котлети з батоном',
    calories: 203.67,
  },
  {
    proteins: 13.49,
    carbohydrates: 5.96,
    fats: 23.18,
    name: 'Котлети з батоном Оля',
    calories: 216.36,
  },
  {
    proteins: 16,
    carbohydrates: 0,
    fats: 0.5,
    name: 'Краб',
    calories: 5.31,
  },
  {
    proteins: 18,
    carbohydrates: 0,
    fats: 0.8,
    name: 'Креветка',
    calories: 8.18,
  },
  {
    proteins: 1.15,
    carbohydrates: 1.82,
    fats: 6.15,
    name: 'Крем-суп bonduelle зелений',
    calories: 57.27,
  },
  {
    proteins: 20.7,
    carbohydrates: 0,
    fats: 12.9,
    name: 'Кролик',
    calories: 120.82,
  },
  {
    proteins: 0.1,
    carbohydrates: 79.6,
    fats: 0,
    name: 'Крохмаль',
    calories: 3.27,
  },
  {
    proteins: 6,
    carbohydrates: 46,
    fats: 26,
    name: 'Круасани 7 days з ваніллю',
    calories: 243.93,
  },
  {
    proteins: 0.7,
    carbohydrates: 9.9,
    fats: 0.2,
    name: 'Аґрус',
    calories: 2.29,
  },
  {
    proteins: 3.12,
    carbohydrates: 12.42,
    fats: 2.59,
    name: 'Кукурудзяна з молоком',
    calories: 24.71,
  },
  {
    proteins: 3.4,
    carbohydrates: 18.6,
    fats: 1.5,
    name: 'Кукурудза варена',
    calories: 14.85,
  },
  {
    proteins: 8.3,
    carbohydrates: 75,
    fats: 1.2,
    name: 'Кукурудзяна',
    calories: 14.58,
  },
  {
    proteins: 5.5,
    carbohydrates: 46.01,
    fats: 13.45,
    name: 'Кулічі Оля',
    calories: 127.17,
  },
  {
    proteins: 5.2,
    carbohydrates: 65.9,
    fats: 0.5,
    name: 'Курага',
    calories: 7.57,
  },
  {
    proteins: 3.7,
    carbohydrates: 23.22,
    fats: 0.16,
    name: 'Кус кус',
    calories: 2.59,
  },
  {
    proteins: 7.93,
    carbohydrates: 51.8,
    fats: 1.43,
    name: 'Лаваш грузинський',
    calories: 15.75,
  },
  {
    proteins: 8.76,
    carbohydrates: 11.41,
    fats: 9.34,
    name: 'Лазанья',
    calories: 87.74,
  },
  {
    proteins: 0.02,
    carbohydrates: 80,
    fats: 2,
    name: 'Цукерки',
    calories: 21.88,
  },
  {
    proteins: 17.1,
    carbohydrates: 0,
    fats: 4.1,
    name: 'Лящ',
    calories: 38.83,
  },
  {
    proteins: 0.9,
    carbohydrates: 3.6,
    fats: 0.3,
    name: 'Лимон',
    calories: 2.97,
  },
  {
    proteins: 0,
    carbohydrates: 9.09,
    fats: 0,
    name: 'Лимонад з цукром',
    calories: 0.37,
  },
  {
    proteins: 13,
    carbohydrates: 70,
    fats: 3.2,
    name: 'Листи лазаньї PastaZara',
    calories: 33.16,
  },
  {
    proteins: 1.5,
    carbohydrates: 2.2,
    fats: 0.1,
    name: 'Листя салату',
    calories: 1.08,
  },
  {
    proteins: 2.5,
    carbohydrates: 13.2,
    fats: 1.5,
    name: 'Локо-моко йогурт банан',
    calories: 14.59,
  },
  {
    proteins: 1.1,
    carbohydrates: 9,
    fats: 0.1,
    name: 'Цибуля',
    calories: 1.34,
  },
  {
    proteins: 1.3,
    carbohydrates: 4.3,
    fats: 0.1,
    name: 'Цибуля зелена (перо)',
    calories: 1.16,
  },
  {
    proteins: 3,
    carbohydrates: 7.3,
    fats: 0.1,
    name: 'Порей',
    calories: 1.35,
  },
  {
    proteins: 12.17,
    carbohydrates: 9.06,
    fats: 16.14,
    name: 'Львівський сирник',
    calories: 150.95,
  },
  {
    proteins: 8.69,
    carbohydrates: 3.71,
    fats: 21.43,
    name: 'Мімоза',
    calories: 199.78,
  },
  {
    proteins: 1.5,
    carbohydrates: 3,
    fats: 76,
    name: 'Майонез',
    calories: 706.98,
  },
  {
    proteins: 0.8,
    carbohydrates: 9,
    fats: 0.7,
    name: 'Малина',
    calories: 6.91,
  },
  {
    proteins: 0.8,
    carbohydrates: 8.6,
    fats: 0.2,
    name: 'Мандарин',
    calories: 2.25,
  },
  {
    proteins: 11.3,
    carbohydrates: 73.3,
    fats: 0.7,
    name: 'Манна',
    calories: 9.98,
  },
  {
    proteins: 0,
    carbohydrates: 77.7,
    fats: 0.1,
    name: 'Мармелад',
    calories: 4.12,
  },
  {
    proteins: 0.5,
    carbohydrates: 0.8,
    fats: 82.5,
    name: 'Масло Наш Молочник 82.5%',
    calories: 767.3,
  },
  {
    proteins: 0,
    carbohydrates: 0,
    fats: 100,
    name: 'Масло рослинне',
    calories: 930,
  },
  {
    proteins: 0.8,
    carbohydrates: 80.3,
    fats: 0,
    name: 'Мед',
    calories: 3.33,
  },
  {
    proteins: 18.6,
    carbohydrates: 13.6,
    fats: 57.7,
    name: 'Мигдаль',
    calories: 537.93,
  },
  {
    proteins: 22.4,
    carbohydrates: 12.6,
    fats: 55.9,
    name: 'Мигдальна мука',
    calories: 521.31,
  },
  {
    proteins: 9.66,
    carbohydrates: 15.35,
    fats: 39.37,
    name: 'Мигдальні кекси',
    calories: 367.15,
  },
  {
    proteins: 14.19,
    carbohydrates: 37.34,
    fats: 32.16,
    name: 'Мигдальне печиво домашнє',
    calories: 301.18,
  },
  {
    proteins: 11,
    carbohydrates: 6,
    fats: 15,
    name: 'Cир кремовий плавлений',
    calories: 140.2,
  },
  {
    proteins: 2.71,
    carbohydrates: 17.61,
    fats: 4.37,
    name: 'Молода картопля з кропом',
    calories: 41.51,
  },
  {
    proteins: 2.8,
    carbohydrates: 4.7,
    fats: 3.2,
    name: 'Молоко',
    calories: 30.07,
  },
  {
    proteins: 1,
    carbohydrates: 6.5,
    fats: 1.5,
    name: 'Молоко мультизлакове vega',
    calories: 14.26,
  },
  {
    proteins: 7.2,
    carbohydrates: 56,
    fats: 8.5,
    name: 'Молоко згущене з цукром',
    calories: 81.64,
  },
  {
    proteins: 2.8,
    carbohydrates: 4.7,
    fats: 3.2,
    name: 'Молоко Селянське Ультрапастеризоване',
    calories: 30.07,
  },
  {
    proteins: 2.95,
    carbohydrates: 14.87,
    fats: 1.42,
    name: 'Морквяники',
    calories: 13.93,
  },
  {
    proteins: 0.9,
    carbohydrates: 6.8,
    fats: 0.2,
    name: 'Морква',
    calories: 2.18,
  },
  {
    proteins: 0.66,
    carbohydrates: 8.95,
    fats: 0.2,
    name: 'Морква з яблуками',
    calories: 2.25,
  },
  {
    proteins: 4.6,
    carbohydrates: 20.4,
    fats: 13.5,
    name: 'Морозиво Три Ведмеді фісташкове',
    calories: 126.58,
  },
  {
    proteins: 0.9,
    carbohydrates: 3,
    fats: 0.2,
    name: 'Морська капуста',
    calories: 2.02,
  },
  {
    proteins: 12,
    carbohydrates: 72,
    fats: 1,
    name: 'Борошно la pasta з твердих сортів',
    calories: 12.74,
  },
  {
    proteins: 10,
    carbohydrates: 76,
    fats: 1,
    name: 'Борошно біле',
    calories: 12.83,
  },
  {
    proteins: 12.2,
    carbohydrates: 72,
    fats: 1,
    name: 'Борошно з твердих сортів',
    calories: 12.75,
  },
  {
    proteins: 10.3,
    carbohydrates: 70,
    fats: 1.1,
    name: 'Борошно пшеничне',
    calories: 13.52,
  },
  {
    proteins: 12.4,
    carbohydrates: 2.42,
    fats: 11.4,
    name: 'Мʼясна начинка для млинців',
    calories: 106.61,
  },
  {
    proteins: 20.8,
    carbohydrates: 0.6,
    fats: 8.8,
    name: 'Мʼясо курки(філе)',
    calories: 82.72,
  },
  {
    proteins: 2.1,
    carbohydrates: 4,
    fats: 0.4,
    name: 'Овочі бондюель для супу зелений',
    calories: 3.97,
  },
  {
    proteins: 2.5,
    carbohydrates: 4.4,
    fats: 0.4,
    name: 'Овочі bonduelle 4 сезона',
    calories: 4,
  },
  {
    proteins: 2.6,
    carbohydrates: 4,
    fats: 6.93,
    name: 'Овочі bonduelle 4 сезона зі сметаною',
    calories: 64.75,
  },
  {
    proteins: 2.26,
    carbohydrates: 6.65,
    fats: 7.02,
    name: 'Овочі тушковані в сметані',
    calories: 65.69,
  },
  {
    proteins: 2.92,
    carbohydrates: 10.32,
    fats: 0.21,
    name: 'Овочева суміш мексиканська',
    calories: 2.5,
  },
  {
    proteins: 4.41,
    carbohydrates: 5.86,
    fats: 2.2,
    name: 'Овочеве рагу в духовці',
    calories: 20.86,
  },
  {
    proteins: 11.9,
    carbohydrates: 55,
    fats: 5.8,
    name: 'Вівсяна',
    calories: 56.68,
  },
  {
    proteins: 2.99,
    carbohydrates: 8.81,
    fats: 2.77,
    name: 'Вівсянка',
    calories: 26.24,
  },
  {
    proteins: 0.8,
    carbohydrates: 3,
    fats: 0.1,
    name: 'Огірки грунтові',
    calories: 1.09,
  },
  {
    proteins: 3.55,
    carbohydrates: 2.92,
    fats: 4.83,
    name: 'Окрошка',
    calories: 45.22,
  },
  {
    proteins: 17.6,
    carbohydrates: 0,
    fats: 5.2,
    name: 'Окунь морський',
    calories: 49.08,
  },
  {
    proteins: 18.5,
    carbohydrates: 0,
    fats: 0.9,
    name: 'Окунь річковий',
    calories: 9.13,
  },
  {
    proteins: 8.09,
    carbohydrates: 5.63,
    fats: 16.3,
    name: 'Олівʼє',
    calories: 152.19,
  },
  {
    proteins: 6.36,
    carbohydrates: 22.68,
    fats: 1.67,
    name: 'Оладки 50×50 борошно тверде та біле',
    calories: 16.69,
  },
  {
    proteins: 3.33,
    carbohydrates: 13.91,
    fats: 1.73,
    name: 'Оладки з кабачків',
    calories: 16.75,
  },
  {
    proteins: 6.4,
    carbohydrates: 22.5,
    fats: 3.71,
    name: 'Оладки з ізюмом',
    calories: 35.73,
  },
  {
    proteins: 5,
    carbohydrates: 21,
    fats: 3,
    name: 'Оладки з яблуком',
    calories: 28.97,
  },
  {
    proteins: 4.91,
    carbohydrates: 22.64,
    fats: 2.81,
    name: 'Оладки з яблуком рецепт',
    calories: 27.24,
  },
  {
    proteins: 9.14,
    carbohydrates: 29.33,
    fats: 6.22,
    name: 'Оладки суфле',
    calories: 59.41,
  },
  {
    proteins: 0.5,
    carbohydrates: 0,
    fats: 15,
    name: 'Оливки зелені',
    calories: 139.52,
  },
  {
    proteins: 6.84,
    carbohydrates: 3.72,
    fats: 8.53,
    name: 'Омлет',
    calories: 79.74,
  },
  {
    proteins: 7.9,
    carbohydrates: 2.9,
    fats: 7.1,
    name: 'Омлет з молоком',
    calories: 66.47,
  },
  {
    proteins: 16.4,
    carbohydrates: 0,
    fats: 10.9,
    name: 'Осетр',
    calories: 102.04,
  },
  {
    proteins: 28.9,
    carbohydrates: 0,
    fats: 9.7,
    name: 'Осетрова зерниста ікра',
    calories: 91.39,
  },
  {
    proteins: 2.8,
    carbohydrates: 15.5,
    fats: 1.7,
    name: 'Палента',
    calories: 16.56,
  },
  {
    proteins: 18.9,
    carbohydrates: 0,
    fats: 3,
    name: 'Палтус',
    calories: 28.67,
  },
  {
    proteins: 38,
    carbohydrates: 4.1,
    fats: 29,
    name: 'Пармезан',
    calories: 271.43,
  },
  {
    proteins: 0.5,
    carbohydrates: 80.4,
    fats: 0,
    name: 'Пастила',
    calories: 3.32,
  },
  {
    proteins: 9.6,
    carbohydrates: 28.2,
    fats: 2.5,
    name: 'Пельмені vici з яловичиною сирі',
    calories: 24.8,
  },
  {
    proteins: 7.68,
    carbohydrates: 24.62,
    fats: 5.45,
    name: 'Пельмені vici з куркою варені',
    calories: 52.03,
  },
  {
    proteins: 9.3,
    carbohydrates: 29.8,
    fats: 6.6,
    name: 'Пельмені vici з куркою сирі',
    calories: 62.98,
  },
  {
    proteins: 12.95,
    carbohydrates: 28.37,
    fats: 11.27,
    name: 'Пельмені Балувана Галя',
    calories: 106.51,
  },
  {
    proteins: 9.71,
    carbohydrates: 21.28,
    fats: 8.45,
    name: 'Пельмені Балувана Галя варені',
    calories: 79.88,
  },
  {
    proteins: 7.55,
    carbohydrates: 22.18,
    fats: 1.97,
    name: 'Пельмені з Vici з яловичиною варені',
    calories: 19.51,
  },
  {
    proteins: 1.3,
    carbohydrates: 4.9,
    fats: 0.1,
    name: 'Перець білозірка',
    calories: 1.18,
  },
  {
    proteins: 1,
    carbohydrates: 6,
    fats: 0.2,
    name: 'Перець болгарський жовтий',
    calories: 2.15,
  },
  {
    proteins: 1,
    carbohydrates: 4.6,
    fats: 0.2,
    name: 'Перець болгарський зелений',
    calories: 2.09,
  },
  {
    proteins: 1.3,
    carbohydrates: 5.3,
    fats: 0.1,
    name: 'Перець болгарський червоний',
    calories: 1.2,
  },
  {
    proteins: 7.1,
    carbohydrates: 3.54,
    fats: 7.62,
    name: 'Перець фарширований сир і рис',
    calories: 71.29,
  },
  {
    proteins: 9.3,
    carbohydrates: 73.7,
    fats: 1.1,
    name: 'Перлова крупа',
    calories: 13.63,
  },
  {
    proteins: 0.9,
    carbohydrates: 10.4,
    fats: 0.3,
    name: 'Персики',
    calories: 3.25,
  },
  {
    proteins: 0.3,
    carbohydrates: 13.9,
    fats: 0.1,
    name: 'Персики консервовані',
    calories: 1.51,
  },
  {
    proteins: 3,
    carbohydrates: 68.5,
    fats: 0.5,
    name: 'Персики сушені',
    calories: 7.58,
  },
  {
    proteins: 8.96,
    carbohydrates: 1.13,
    fats: 6.25,
    name: 'Перці фаршировані з сиром',
    calories: 58.49,
  },
  {
    proteins: 3.7,
    carbohydrates: 8.1,
    fats: 0.1,
    name: 'Петрушка (зелень)',
    calories: 1.41,
  },
  {
    proteins: 1.5,
    carbohydrates: 11,
    fats: 0.1,
    name: 'Петрушка (корінь)',
    calories: 1.44,
  },
  {
    proteins: 12.62,
    carbohydrates: 10.31,
    fats: 4.96,
    name: 'Печінкові оладки',
    calories: 47.06,
  },
  {
    proteins: 20.4,
    carbohydrates: 0.73,
    fats: 5.9,
    name: 'Печінка куряча',
    calories: 55.74,
  },
  {
    proteins: 12.19,
    carbohydrates: 2.83,
    fats: 8.85,
    name: 'Печінка куряча в сметані',
    calories: 82.9,
  },
  {
    proteins: 18.8,
    carbohydrates: 0,
    fats: 3.6,
    name: 'Печінка свиняча',
    calories: 34.25,
  },
  {
    proteins: 4.2,
    carbohydrates: 0,
    fats: 65.7,
    name: 'Печінка тріски',
    calories: 611.18,
  },
  {
    proteins: 8.8,
    carbohydrates: 38.04,
    fats: 18.85,
    name: 'Печиво гусині лапки',
    calories: 177.21,
  },
  {
    proteins: 11.63,
    carbohydrates: 29.34,
    fats: 38.33,
    name: 'Печиво кокосанка',
    calories: 358.11,
  },
  {
    proteins: 6.23,
    carbohydrates: 66,
    fats: 11.5,
    name: 'Печиво коржик',
    calories: 109.91,
  },
  {
    proteins: 10.6,
    carbohydrates: 60.4,
    fats: 14.9,
    name: 'Печиво Марія цілезернове',
    calories: 141.48,
  },
  {
    proteins: 7.6,
    carbohydrates: 78,
    fats: 2.8,
    name: 'Печиво савоярді',
    calories: 29.55,
  },
  {
    proteins: 0.5,
    carbohydrates: 3.6,
    fats: 0,
    name: 'Пиво',
    calories: 0.17,
  },
  {
    proteins: 5.15,
    carbohydrates: 28.16,
    fats: 12.8,
    name: 'Пиріг з грушею',
    calories: 120.36,
  },
  {
    proteins: 6,
    carbohydrates: 33.66,
    fats: 24.2,
    name: 'Пиріг Зебра',
    calories: 226.69,
  },
  {
    proteins: 5.9,
    carbohydrates: 39.27,
    fats: 6.21,
    name: 'Пиріг з яблуками на кефірі',
    calories: 59.6,
  },
  {
    proteins: 8.47,
    carbohydrates: 18,
    fats: 8.56,
    name: 'Плов',
    calories: 80.69,
  },
  {
    proteins: 4.7,
    carbohydrates: 50,
    fats: 24,
    name: 'Плюшка',
    calories: 225.44,
  },
  {
    proteins: 5,
    carbohydrates: 4,
    fats: 18,
    name: 'Підлива бефстроганов',
    calories: 167.77,
  },
  {
    proteins: 5.22,
    carbohydrates: 4.37,
    fats: 10.99,
    name: 'Підливка бефстроганов(рецепт)',
    calories: 102.57,
  },
  {
    proteins: 0.6,
    carbohydrates: 4.2,
    fats: 0.1,
    name: 'Помідор',
    calories: 1.13,
  },
  {
    proteins: 10,
    carbohydrates: 40,
    fats: 20,
    name: 'Пампушка',
    calories: 188.05,
  },
  {
    proteins: 1,
    carbohydrates: 11,
    fats: 1,
    name: 'Попкорн',
    calories: 9.79,
  },
  {
    proteins: 10,
    carbohydrates: 25,
    fats: 11,
    name: 'Попкорн солоний',
    calories: 103.74,
  },
  {
    proteins: 13,
    carbohydrates: 0,
    fats: 3.1,
    name: 'Нирки свинячі',
    calories: 29.36,
  },
  {
    proteins: 2.8,
    carbohydrates: 4.1,
    fats: 3.2,
    name: 'Простокваша',
    calories: 30.04,
  },
  {
    proteins: 12,
    carbohydrates: 69.3,
    fats: 2.9,
    name: 'Пшоно',
    calories: 30.3,
  },
  {
    proteins: 6.3,
    carbohydrates: 7.56,
    fats: 5.04,
    name: 'Рагу в духовці',
    calories: 47.44,
  },
  {
    proteins: 1.2,
    carbohydrates: 4.1,
    fats: 0.1,
    name: 'Редис',
    calories: 1.15,
  },
  {
    proteins: 1.9,
    carbohydrates: 7,
    fats: 0.1,
    name: 'Редька',
    calories: 1.29,
  },
  {
    proteins: 1.5,
    carbohydrates: 5.9,
    fats: 0.1,
    name: 'Ріпа',
    calories: 1.23,
  },
  {
    proteins: 8.78,
    carbohydrates: 11.83,
    fats: 4.92,
    name: 'Ризотто',
    calories: 46.6,
  },
  {
    proteins: 10.1,
    carbohydrates: 78.2,
    fats: 6.1,
    name: 'Рис басматі',
    calories: 60.35,
  },
  {
    proteins: 3.13,
    carbohydrates: 24.27,
    fats: 1.89,
    name: 'Рис варений',
    calories: 18.73,
  },
  {
    proteins: 7.6,
    carbohydrates: 76.9,
    fats: 2.9,
    name: 'Рис червоний',
    calories: 30.43,
  },
  {
    proteins: 7,
    carbohydrates: 73.7,
    fats: 0.6,
    name: 'Рисова крупа',
    calories: 8.89,
  },
  {
    proteins: 4.01,
    carbohydrates: 3.95,
    fats: 5.69,
    name: 'Рецепт Капуста тушована',
    calories: 53.27,
  },
  {
    proteins: 3,
    carbohydrates: 4.1,
    fats: 6,
    name: 'Ряжанка',
    calories: 56.09,
  },
  {
    proteins: 18.4,
    carbohydrates: 0,
    fats: 5.3,
    name: 'Сазан',
    calories: 50.04,
  },
  {
    proteins: 2.5,
    carbohydrates: 3.22,
    fats: 5.42,
    name: 'Салат грецький',
    calories: 50.61,
  },
  {
    proteins: 4.69,
    carbohydrates: 3.3,
    fats: 6.92,
    name: 'Салат сметана огірки помідори',
    calories: 64.68,
  },
  {
    proteins: 2.75,
    carbohydrates: 1,
    fats: 84.44,
    name: 'Сало',
    calories: 785.45,
  },
  {
    proteins: 0,
    carbohydrates: 100,
    fats: 0,
    name: 'Цукор',
    calories: 4.1,
  },
  {
    proteins: 1.6,
    carbohydrates: 10,
    fats: 0.2,
    name: 'Буряк',
    calories: 2.34,
  },
  {
    proteins: 11.4,
    carbohydrates: 0,
    fats: 49.3,
    name: 'Свинина жирна',
    calories: 458.96,
  },
  {
    proteins: 16.4,
    carbohydrates: 0,
    fats: 27.8,
    name: 'Свинина не жирна',
    calories: 259.21,
  },
  {
    proteins: 0.6,
    carbohydrates: 7,
    fats: 0.2,
    name: 'Світі',
    calories: 2.17,
  },
  {
    proteins: 24.4,
    carbohydrates: 0,
    fats: 30.2,
    name: 'Сир Королівський',
    calories: 281.86,
  },
  {
    proteins: 17.7,
    carbohydrates: 0,
    fats: 19.5,
    name: 'Оселедець',
    calories: 182.08,
  },
  {
    proteins: 20.8,
    carbohydrates: 0,
    fats: 15.1,
    name: 'Лосось',
    calories: 141.28,
  },
  {
    proteins: 20.7,
    carbohydrates: 5,
    fats: 52.9,
    name: 'Соняшникові насіння',
    calories: 493.02,
  },
  {
    proteins: 15.1,
    carbohydrates: 0,
    fats: 3.2,
    name: 'Серце свиняче',
    calories: 30.38,
  },
  {
    proteins: 26,
    carbohydrates: 0,
    fats: 27,
    name: 'Сир Morski',
    calories: 252.17,
  },
  {
    proteins: 18,
    carbohydrates: 0,
    fats: 9,
    name: 'Скумбрія',
    calories: 84.44,
  },
  {
    proteins: 0.8,
    carbohydrates: 9.9,
    fats: 0.3,
    name: 'Слива садова',
    calories: 3.23,
  },
  {
    proteins: 3,
    carbohydrates: 4,
    fats: 10,
    name: 'Збиті вершки 10%',
    calories: 93.29,
  },
  {
    proteins: 2.8,
    carbohydrates: 3.6,
    fats: 20,
    name: 'Збиті вершки 20%',
    calories: 186.26,
  },
  {
    proteins: 2.1,
    carbohydrates: 2,
    fats: 33,
    name: 'Збиті вершки 33%',
    calories: 307.07,
  },
  {
    proteins: 3,
    carbohydrates: 2.9,
    fats: 10,
    name: 'Сметана 10%',
    calories: 93.24,
  },
  {
    proteins: 2.8,
    carbohydrates: 3.2,
    fats: 20,
    name: 'Сметана 20%',
    calories: 186.25,
  },
  {
    proteins: 0.3,
    carbohydrates: 8.7,
    fats: 0.4,
    name: 'Смородина біла',
    calories: 4.09,
  },
  {
    proteins: 0.6,
    carbohydrates: 8,
    fats: 0.4,
    name: 'Смородина червона',
    calories: 4.07,
  },
  {
    proteins: 1,
    carbohydrates: 8,
    fats: 0.4,
    name: 'Смородина чорна',
    calories: 4.09,
  },
  {
    proteins: 0.97,
    carbohydrates: 12.8,
    fats: 0.3,
    name: 'Смузі',
    calories: 3.35,
  },
  {
    proteins: 10,
    carbohydrates: 3.2,
    fats: 0,
    name: 'Соєвий соус',
    calories: 0.54,
  },
  {
    proteins: 0.1,
    carbohydrates: 11.6,
    fats: 0,
    name: 'Сік Galicia Яблуко-груша',
    calories: 0.48,
  },
  {
    proteins: 0,
    carbohydrates: 12.3,
    fats: 0,
    name: 'Сік Агуша Яблуко-шиповник',
    calories: 0.5,
  },
  {
    proteins: 16.8,
    carbohydrates: 0,
    fats: 8.5,
    name: 'Сом',
    calories: 79.74,
  },
  {
    proteins: 34.9,
    carbohydrates: 26.5,
    fats: 17.3,
    name: 'Соя',
    calories: 163.41,
  },
  {
    proteins: 5.65,
    carbohydrates: 31.31,
    fats: 0.88,
    name: 'Спагетті Barilla варені',
    calories: 9.73,
  },
  {
    proteins: 12.8,
    carbohydrates: 70.9,
    fats: 2,
    name: 'Спагеті Barrilla #5',
    calories: 22.03,
  },
  {
    proteins: 18.5,
    carbohydrates: 0,
    fats: 5,
    name: 'Ставрида',
    calories: 47.26,
  },
  {
    proteins: 17,
    carbohydrates: 0,
    fats: 6.1,
    name: 'Стерлядь',
    calories: 57.43,
  },
  {
    proteins: 19,
    carbohydrates: 0,
    fats: 0.8,
    name: 'Судак',
    calories: 8.22,
  },
  {
    proteins: 3.74,
    carbohydrates: 2.19,
    fats: 1.77,
    name: 'Суп із фрикадельками',
    calories: 16.69,
  },
  {
    proteins: 3.4,
    carbohydrates: 2.61,
    fats: 2.05,
    name: 'Суп харчо',
    calories: 19.3,
  },
  {
    proteins: 1.56,
    carbohydrates: 2.48,
    fats: 4.16,
    name: 'Суп-пюре bonduelle бежевий',
    calories: 38.85,
  },
  {
    proteins: 11.2,
    carbohydrates: 80.7,
    fats: 1.4,
    name: 'Сухарі домашні',
    calories: 16.79,
  },
  {
    proteins: 9.6,
    carbohydrates: 73.8,
    fats: 10.9,
    name: 'Сушки Київські',
    calories: 104.79,
  },
  {
    proteins: 6.3,
    carbohydrates: 34,
    fats: 13,
    name: 'Сир Philadelphia milka',
    calories: 122.55,
  },
  {
    proteins: 25,
    carbohydrates: 1.5,
    fats: 27,
    name: 'Сир Salami з помідорами',
    calories: 252.19,
  },
  {
    proteins: 26.8,
    carbohydrates: 0,
    fats: 27.3,
    name: 'Сир голландський',
    calories: 254.99,
  },
  {
    proteins: 25.3,
    carbohydrates: 2.34,
    fats: 29,
    name: 'Сир ДорБлю Grand Noir',
    calories: 270.83,
  },
  {
    proteins: 21,
    carbohydrates: 2.34,
    fats: 30,
    name: 'Сир ДорБлю Kaserei',
    calories: 279.96,
  },
  {
    proteins: 27.5,
    carbohydrates: 0,
    fats: 21.2,
    name: 'Сир Комо Тенеро',
    calories: 198.29,
  },
  {
    proteins: 4.5,
    carbohydrates: 4,
    fats: 41,
    name: 'Сир маскарпоне',
    calories: 381.65,
  },
  {
    proteins: 28,
    carbohydrates: 3.1,
    fats: 17,
    name: 'Сир моцарелла',
    calories: 159.38,
  },
  {
    proteins: 26,
    carbohydrates: 0,
    fats: 26.5,
    name: 'Сир пошехонський',
    calories: 247.52,
  },
  {
    proteins: 23.4,
    carbohydrates: 0,
    fats: 30,
    name: 'Сир російський',
    calories: 279.96,
  },
  {
    proteins: 10,
    carbohydrates: 4,
    fats: 23,
    name: 'Сир Філадельфія',
    calories: 214.47,
  },
  {
    proteins: 24.9,
    carbohydrates: 0,
    fats: 31.8,
    name: 'Сир швейцарський',
    calories: 296.76,
  },
  {
    proteins: 14.68,
    carbohydrates: 18.3,
    fats: 7.23,
    name: 'Сирники з білою мукою та стевією',
    calories: 68.58,
  },
  {
    proteins: 15.19,
    carbohydrates: 12.43,
    fats: 8.01,
    name: 'Сирники з цукром',
    calories: 75.63,
  },
  {
    proteins: 16.85,
    carbohydrates: 1.6,
    fats: 13.02,
    name: 'Сирно-мʼясний рулет',
    calories: 121.83,
  },
  {
    proteins: 17.29,
    carbohydrates: 20.73,
    fats: 10.8,
    name: 'Сирні палички',
    calories: 102,
  },
  {
    proteins: 14,
    carbohydrates: 1.3,
    fats: 18,
    name: 'Творог жирний',
    calories: 168.03,
  },
  {
    proteins: 18,
    carbohydrates: 1.5,
    fats: 0.6,
    name: 'Творог нежирний',
    calories: 6.38,
  },
  {
    proteins: 16.7,
    carbohydrates: 2,
    fats: 9,
    name: 'Творог півжирний',
    calories: 84.47,
  },
  {
    proteins: 16.2,
    carbohydrates: 2,
    fats: 10,
    name: 'Творог Простоквашино',
    calories: 93.75,
  },
  {
    proteins: 12.31,
    carbohydrates: 6.85,
    fats: 9.05,
    name: 'Творожна запіканка',
    calories: 84.98,
  },
  {
    proteins: 12.95,
    carbohydrates: 3.59,
    fats: 12.16,
    name: 'Творожна запіканка з малиною',
    calories: 113.74,
  },
  {
    proteins: 14.13,
    carbohydrates: 8.36,
    fats: 14.48,
    name: 'Творожна начинка для млинців',
    calories: 135.55,
  },
  {
    proteins: 14.38,
    carbohydrates: 15.8,
    fats: 8.49,
    name: 'Творожні бублики',
    calories: 80.23,
  },
  {
    proteins: 8.99,
    carbohydrates: 5.82,
    fats: 6.05,
    name: 'Творожні суфле',
    calories: 56.91,
  },
  {
    proteins: 8.9,
    carbohydrates: 31.61,
    fats: 18.54,
    name: 'Творожний кекс',
    calories: 174.12,
  },
  {
    proteins: 19.7,
    carbohydrates: 0,
    fats: 1.2,
    name: 'Телятина',
    calories: 11.97,
  },
  {
    proteins: 10.09,
    carbohydrates: 8.69,
    fats: 7.82,
    name: 'Тефтелі',
    calories: 73.46,
  },
  {
    proteins: 4,
    carbohydrates: 16.4,
    fats: 0,
    name: 'Томатна паста Чумак 25%',
    calories: 0.84,
  },
  {
    proteins: 4.45,
    carbohydrates: 28.64,
    fats: 14.49,
    name: 'Торт бісквітний',
    calories: 136.15,
  },
  {
    proteins: 5.46,
    carbohydrates: 37.25,
    fats: 8.41,
    name: 'Торт бісквітний новий',
    calories: 79.94,
  },
  {
    proteins: 4.75,
    carbohydrates: 35.88,
    fats: 21.83,
    name: 'Торт Наполеон',
    calories: 204.68,
  },
  {
    proteins: 3.98,
    carbohydrates: 22.89,
    fats: 27.96,
    name: 'Торт Тирамісу домашній',
    calories: 261.17,
  },
  {
    proteins: 17.5,
    carbohydrates: 0,
    fats: 0.6,
    name: 'Тріска',
    calories: 6.3,
  },
  {
    proteins: 22.7,
    carbohydrates: 0,
    fats: 0.7,
    name: 'Тунець',
    calories: 7.44,
  },
  {
    proteins: 5.68,
    carbohydrates: 6.3,
    fats: 5.92,
    name: 'Тушковані овочі в духовці',
    calories: 55.57,
  },
  {
    proteins: 1.3,
    carbohydrates: 8,
    fats: 0.3,
    name: 'Гарбуз',
    calories: 3.17,
  },
  {
    proteins: 3.93,
    carbohydrates: 24.79,
    fats: 12.4,
    name: 'Гарбузовий пиріг',
    calories: 116.51,
  },
  {
    proteins: 14.5,
    carbohydrates: 0,
    fats: 30.5,
    name: 'Вугор',
    calories: 284.24,
  },
  {
    proteins: 19.1,
    carbohydrates: 0,
    fats: 1.9,
    name: 'Морський вугор',
    calories: 18.45,
  },
  {
    proteins: 16,
    carbohydrates: 55,
    fats: 15,
    name: 'Кріп',
    calories: 142.41,
  },
  {
    proteins: 5,
    carbohydrates: 67.5,
    fats: 0.5,
    name: 'Урюк',
    calories: 7.62,
  },
  {
    proteins: 16.5,
    carbohydrates: 0,
    fats: 61.2,
    name: 'Качки',
    calories: 569.84,
  },
  {
    proteins: 27,
    carbohydrates: 0,
    fats: 4,
    name: 'Філе індика',
    calories: 38.31,
  },
  {
    proteins: 22.3,
    carbohydrates: 54.5,
    fats: 1.7,
    name: 'Фасоль',
    calories: 18.96,
  },
  {
    proteins: 12.1,
    carbohydrates: 2.5,
    fats: 17.1,
    name: 'Фета',
    calories: 159.63,
  },
  {
    proteins: 2.5,
    carbohydrates: 72.1,
    fats: 0.5,
    name: 'Фініки',
    calories: 7.71,
  },
  {
    proteins: 20,
    carbohydrates: 28,
    fats: 45,
    name: 'Фісташки',
    calories: 420.47,
  },
  {
    proteins: 16.1,
    carbohydrates: 9.9,
    fats: 66.9,
    name: 'Фундук, Горіх лісовий',
    calories: 623.24,
  },
  {
    proteins: 11.6,
    carbohydrates: 54,
    fats: 29.7,
    name: 'Соняшникова халва',
    calories: 278.9,
  },
  {
    proteins: 12.7,
    carbohydrates: 50.6,
    fats: 29.9,
    name: 'Тахінна халва',
    calories: 280.67,
  },
  {
    proteins: 20,
    carbohydrates: 0.4,
    fats: 13,
    name: 'Хамон',
    calories: 121.74,
  },
  { proteins: 16.6, carbohydrates: 0, fats: 2.2, name: 'Хек', calories: 21.14 },
  { proteins: 0, carbohydrates: 0, fats: 0, name: 'Хінкалі', calories: 0 },
  { proteins: 12.2, carbohydrates: 41.4, fats: 0.96, name: 'Хліб здоровʼя "просто добрий"', calories: 11.13 },
  { proteins: 8.8, carbohydrates: 56.9, fats: 3.7, name: 'Хліб зерновий', calories: 37.1 },
  { proteins: 7.4, carbohydrates: 50.1, fats: 0.9, name: 'Хліб литовський', calories: 10.73 },
  { proteins: 7.4, carbohydrates: 54.5, fats: 1.09, name: 'Хліб бездріжджовий "просто добрий"', calories: 12.67 },
  { proteins: 7.2, carbohydrates: 44.9, fats: 1.3, name: 'Хліб Бородинський Румʼянець', calories: 14.23 },
  { proteins: 8.01, carbohydrates: 48.64, fats: 1.54, name: 'Хліб сабіа', calories: 16.64 },
  { proteins: 8.2, carbohydrates: 60.3, fats: 4.8, name: 'Хліб тостовий', calories: 47.45 },
  { proteins: 8.2, carbohydrates: 60.3, fats: 4.8, name: 'Хліб тостовий', calories: 47.45 },
  { proteins: 6, carbohydrates: 86, fats: 1.2, name: 'Пластівці Старт', calories: 14.93 },
  { proteins: 0.5, carbohydrates: 15.9, fats: 0.4, name: 'Хурма', calories: 4.39 },
  { proteins: 3, carbohydrates: 16.56, fats: 0.3, name: 'Хурма шарон', calories: 3.59 },
  { proteins: 2, carbohydrates: 5, fats: 0.3, name: 'Кольорова капуста', calories: 3.08 },
  { proteins: 18.7, carbohydrates: 0.4, fats: 7.8, name: 'Курчата', calories: 73.32 },
  { proteins: 1.1, carbohydrates: 12.3, fats: 0.4, name: 'Черешня', calories: 4.27 },
  { proteins: 1.1, carbohydrates: 8.6, fats: 0.6, name: 'Чорниця', calories: 5.98 },
  { proteins: 2.3, carbohydrates: 65.6, fats: 0.4, name: 'Слива сушена', calories: 6.5 },
  { proteins: 6.5, carbohydrates: 21.2, fats: 0.1, name: 'Часник', calories: 2.07 },
  { proteins: 24.8, carbohydrates: 53.7, fats: 1.1, name: 'Лінза', calories: 13.45 },
  { proteins: 16, carbohydrates: 30, fats: 13, name: 'Чізбургер', calories: 122.79 },
  {
    proteins: 7.35,
    carbohydrates: 19.62,
    fats: 19.04,
    name: 'Чізкейк',
    calories: 178.17,
  },
  {
    proteins: 6,
    carbohydrates: 26,
    fats: 23,
    name: 'Чізкейк',
    calories: 215.21,
  },
  {
    proteins: 7.4,
    carbohydrates: 19.64,
    fats: 18.93,
    name: 'Чізкейк домашній',
    calories: 177.17,
  },
  {
    proteins: 4.89,
    carbohydrates: 38.29,
    fats: 2.55,
    name: 'Шарлотка',
    calories: 25.47,
  },
  {
    proteins: 2.63,
    carbohydrates: 10.71,
    fats: 5.4,
    name: 'Шейк',
    calories: 50.74,
  },
  {
    proteins: 0.7,
    carbohydrates: 12.7,
    fats: 0.4,
    name: 'Шовковиця',
    calories: 4.27,
  },
  {
    proteins: 6.9,
    carbohydrates: 52.4,
    fats: 35.7,
    name: 'Шоколад молочний',
    calories: 334.44,
  },
  {
    proteins: 5.4,
    carbohydrates: 52.6,
    fats: 35.3,
    name: 'Шоколад темний',
    calories: 330.67,
  },
  {
    proteins: 2.9,
    carbohydrates: 2.3,
    fats: 0.1,
    name: 'Шпинат',
    calories: 1.14,
  },
  {
    proteins: 4.37,
    carbohydrates: 2.84,
    fats: 2.36,
    name: 'Шурпа',
    calories: 22.22,
  },
  {
    proteins: 1.5,
    carbohydrates: 5.3,
    fats: 0.1,
    name: 'Щавель',
    calories: 1.21,
  },
  {
    proteins: 18.8,
    carbohydrates: 0,
    fats: 0.7,
    name: 'Щука',
    calories: 7.28,
  },
  {
    proteins: 0.4,
    carbohydrates: 11.3,
    fats: 0.2,
    name: 'Яблука',
    calories: 2.34,
  },
  {
    proteins: 3.2,
    carbohydrates: 68,
    fats: 0.5,
    name: 'Яблука сушені',
    calories: 7.57,
  },
  {
    proteins: 14.2,
    carbohydrates: 0,
    fats: 16.8,
    name: 'Язик свинячий',
    calories: 156.82,
  },
  {
    proteins: 13,
    carbohydrates: 1.1,
    fats: 11,
    name: 'Яйце',
    calories: 102.88,
  },
  {
    proteins: 11.9,
    carbohydrates: 0.6,
    fats: 13.1,
    name: 'Яйце перепелине',
    calories: 122.34,
  },
  {
    proteins: 10.4,
    carbohydrates: 71.7,
    fats: 1.3,
    name: 'Ячмінна',
    calories: 15.46,
  },
];

export async function up(pgm: MigrationBuilder): Promise<void> {
  pgm.createExtension('pg_trgm', { ifNotExists: true });

  pgm.createTable('products', {
    id: {
      type: 'uuid',
      primaryKey: true,
      default: pgm.func('uuid_generate_v4()'),
    },
    proteins: {
      type: 'real',
      notNull: true,
    },
    carbohydrates: {
      type: 'real',
      notNull: true,
    },
    fats: {
      type: 'real',
      notNull: true,
    },
    title: {
      type: 'varchar(50)',
      notNull: true,
    },
    user_id: {
      type: 'uuid',
      notNull: true,
      references: 'users(id)',
      onDelete: 'CASCADE',
    },
    barcode: {
      type: 'varchar(20)',
      notNull: false,
    },
    description: {
      type: 'text',
      notNull: false,
    },
    created_at: {
      type: 'timestamp',
      notNull: true,
      default: pgm.func('current_timestamp'),
    },
    updated_at: {
      type: 'timestamp',
      notNull: true,
      default: pgm.func('current_timestamp'),
    },
  });

  pgm.sql(`
    CREATE INDEX idx_products_title_gin
    ON products
    USING gin (title gin_trgm_ops);
  `);

  pgm.createConstraint('products', 'unique_product_combination', {
    unique: ['proteins', 'carbohydrates', 'fats', 'title'],
  });

  pgm.sql(`
    INSERT INTO products (proteins, carbohydrates, fats, title, user_id)
    VALUES
    ${getUniqueItems(db, 'name').reduce((acc, item) => {
      return `${acc}${acc === '' ? '' : ', '}(${item.proteins}, ${item.carbohydrates}, ${item.fats}, '${
        item.name
      }', '489ed895-fb78-47f5-87e3-764f6137b379')`;
    }, '')};
  `);
}

export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`
    DROP INDEX IF EXISTS idx_products_title_gin;
  `);
  pgm.dropConstraint('products', 'unique_product_combination');
  pgm.dropTable('products');
}
